import me.modmuss50.mpp.ReleaseType

plugins {
    alias libs.plugins.fabric.loom
    id 'maven-publish'
    alias libs.plugins.lombok
    alias libs.plugins.spotless
    alias libs.plugins.modmuss50.publish
    id 'andromeda-modules'
}

def targetJavaVersion = Integer.parseInt(java_version)
def local = !System.getenv().containsKey("GITHUB_RUN_NUMBER")

version = "${mod_version}+mc${minecraft_version}"
group = project.maven_group

base {
    archivesName = "${project.mod_id}-${loader_id}"
}

apply from: "https://raw.githubusercontent.com/constellation-mc/artifacts/main/artifacts.groovy"
constellationRepo(project, "pulsar")

repositories {
    mavenLocal()
    exclusiveContent {
        forRepository {
            maven { url = 'https://maven.parchmentmc.org/' }
        }
        filter { includeGroup('org.parchmentmc.data') }
    }
    exclusiveContent {
        forRepository {
            maven { url = 'https://maven.shedaniel.me/' }
        }
        filter { includeGroupAndSubgroups('me.shedaniel') }
    }
    exclusiveContent {
        forRepository {
            maven { url = 'https://maven.terraformersmc.com/releases/' }
        }
        filter { includeGroup('com.terraformersmc') }
    }
    mavenCentral()
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation libs.fabric.loader

    modImplementation libs.fabric.api
    modImplementation libs.pulsar

    [libs.modmenu, libs.cloth.config].each {
        modLocalRuntime it
        modCompileOnly it
    }
}

spotless {
    java {
        removeUnusedImports()
        palantirJavaFormat('2.91.0').style("GOOGLE")
        trimTrailingWhitespace()
        formatAnnotations()

        targetExclude(fileTree(layout.buildDirectory.dir("generated")))
    }
}

loom {
    accessWidenerPath = file("src/main/resources/andromeda.accesswidener")

    runs {
        client {
            runDirectory = file("run/client")
        }
        server {
            runDirectory = file("run/server")
        }
    }

    //https://gist.github.com/maityyy/3dbcd558d58a6412c3a2a38c72706e8e
    afterEvaluate {
        loom.runs.configureEach {
            jvmArguments.addAll(["-XX:+IgnoreUnrecognizedVMOptions", "-XX:+AllowEnhancedClassRedefinition"])
            jvmArguments.add("-javaagent:${ configurations.compileClasspath.find { it.name.contains("sponge-mixin") } }")

            systemProperties.put("mixin.debug.export", "true")
        }
    }
}

loom.mods.register(mod_id) {
    sourceSet project.sourceSets.main
}

def generatedSrcDir = layout.buildDirectory.dir("generated/templates/main/java")
tasks.register("processJavaSources", Copy) {
    from("src/template/java")
    into(generatedSrcDir)
    expand(
            "mod_version": mod_version,
            "mod_id": mod_id,
            "minecraft_version": minecraft_version,
    )
    filteringCharset = "UTF-8"
}
tasks.named("compileJava") {
    dependsOn("processJavaSources")
}
sourceSets {
    main {
        java {
            srcDir(generatedSrcDir)
        }
    }
}

processResources {
    def map = [
            "version": project.version,
            "mod_id": mod_id,
            "minecraft_version": minecraft_version,
            "loader_version": libs.fabric.loader.get().version,
            "fabric_version": libs.fabric.api.get().version,
            "cloth_version": libs.cloth.config.get().version,
            "modmenu_version": libs.modmenu.get().version,
            "pulsar_version": libs.pulsar.get().version
    ]
    inputs.properties(map)
    filteringCharset = "UTF-8"

    filesMatching("fabric.mod.json") {
        expand map
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = targetJavaVersion
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${mod_id}" }
    }
}

sourcesJar {
    dependsOn("processJavaSources")
    exclude {
        sourceSets.main.allSource.contains it.file
    }
    from delombok
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = "${mod_id}-${loader_id}"
            from components.java
        }
    }

    if (!local) {
        repositories {
            maven {
                name = "GitHubPackages"
                url = "https://maven.pkg.github.com/constellation-mc/andromeda"
                credentials {
                    username = System.getenv("GITHUB_ACTOR")
                    password = System.getenv("GITHUB_TOKEN")
                }
            }
        }
    }
}

publishMods {
    file = remapJar.archiveFile
    additionalFiles.from(remapSourcesJar.archiveFile)
    version = "${mod_version}+mc${minecraft_version}+${loader_id}"

    changelog = file("CHANGELOG.md").text
    type = ReleaseType.valueOf(providers.environmentVariable("VERSION_TYPE").getOrElse("BETA"))
    modLoaders.add(loader_id)

    displayName = "${mod_version} (${minecraft_version})"

    modrinth {
        projectId = "TseYlb0f"
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersions.add("${minecraft_version}")
        environment = CLIENT_OR_SERVER

        requires("fabric-api")
        requires("pulsar")
        optional("cloth-config")
        optional("modmenu")
    }
    curseforge {
        projectId = "639198"
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        minecraftVersions.add("${minecraft_version}")
        client = true
        server = true

        requires("fabric-api")
        requires("pulsar")
        optional("cloth-config")
        optional("modmenu")
    }
    github {
        repository = "constellation-mc/andromeda"
        accessToken = providers.environmentVariable("GITHUB_TOKEN")
        commitish = providers.environmentVariable("GITHUB_SHA").getOrElse("${minecraft_version}-${loader_id}")

        type = STABLE
    }

    dryRun = local
}