import me.modmuss50.mpp.ReleaseType

plugins {
    alias libs.plugins.fabric.loom
    id 'maven-publish'
    alias libs.plugins.lombok
    alias libs.plugins.spotless
    alias libs.plugins.modmuss50.publish
}

def local = !System.getenv().containsKey("GITHUB_RUN_NUMBER")

version = "${project.mod_version}-${project.minecraft_version}-${local ? 'local' : "build.${System.getenv("GITHUB_RUN_NUMBER")}"}"
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

apply from: "https://raw.githubusercontent.com/constellation-mc/artifacts/main/artifacts.groovy"
constellationRepo(project, "pulsar")
constellationRepo(project, "commander")

repositories {
    mavenLocal()
    maven { url = 'https://maven.parchmentmc.org' }
    maven { url = "https://maven.shedaniel.me/" }
    maven { url = "https://maven.terraformersmc.com/releases/" }
    mavenCentral()
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content { includeGroup "maven.modrinth" }
    }
    maven { url = 'https://jitpack.io' }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-1.21.10:2025.10.12@zip")
    }
    modImplementation libs.fabric.loader

    modImplementation libs.fabric.api
    modImplementation libs.pulsar

    [libs.modmenu, libs.cloth.config].each {
        modLocalRuntime it
        modCompileOnly it
    }
}

spotless {
    java {
        removeUnusedImports()
        palantirJavaFormat('2.91.0').style("GOOGLE")
        trimTrailingWhitespace()
        formatAnnotations()
    }
}

loom {
    accessWidenerPath = file("src/main/resources/andromeda.accesswidener")

    runs {
        client {
            runDir("run_client")
        }
        server {
            runDir("run_server")
        }
    }

    //https://gist.github.com/maityyy/3dbcd558d58a6412c3a2a38c72706e8e
    afterEvaluate {
        loom.runs.configureEach {
            vmArgs("-XX:+IgnoreUnrecognizedVMOptions", "-XX:+AllowEnhancedClassRedefinition")

            vmArg "-javaagent:${ configurations.compileClasspath.find { it.name.contains("sponge-mixin") } }"
            property("mixin.debug.export", "true")
            property("fabric-tag-conventions-v2.missingTagTranslationWarning", "VERBOSE")
        }
    }
}

loom.mods.register(project.archives_base_name) {
    sourceSet project.sourceSets.main
}

processResources {
    def map = [
            "version": project.version,
            "minecraft_version": project.minecraft_version,
            "loader_version": libs.fabric.loader.get().version,
            "fabric_version": libs.fabric.api.get().version,
            "cloth_version": libs.cloth.config.get().version,
            "modmenu_version": libs.modmenu.get().version,
            "pulsar_version": libs.pulsar.get().version
    ]
    inputs.properties(map)
    filteringCharset = "UTF-8"

    filesMatching("fabric.mod.json") {
        expand map
    }
}

def targetJavaVersion = 17
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = targetJavaVersion
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${base.archivesName.get()}" }
    }
}

sourcesJar {
    exclude {
        sourceSets.main.allSource.contains it.file
    }
    from delombok
}

tasks.register('printVersionName') {
    doLast {
        println "${project.mod_version} (${project.minecraft_version})"
    }
}

tasks.register('printVersion') {
    doLast {
        println version
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    if (!local) {
        repositories {
            maven {
                name = "GitHubPackages"
                url = "https://maven.pkg.github.com/constellation-mc/andromeda"
                credentials {
                    username = System.getenv("GITHUB_ACTOR")
                    password = System.getenv("GITHUB_TOKEN")
                }
            }
        }
    }
}

publishMods {
    file = remapJar.archiveFile
    additionalFiles.from(remapSourcesJar.archiveFile)

    changelog = file("CHANGELOG.md").text
    type = ReleaseType.valueOf(providers.environmentVariable("VERSION_TYPE").getOrElse("BETA"))
    modLoaders.add("fabric")

    displayName = "${project.mod_version} (${project.minecraft_version})"

    modrinth {
        projectId = "TseYlb0f"
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersions.add("${project.minecraft_version}")

        requires("fabric-api")
        requires("pulsar")
        optional("cloth-config")
        optional("modmenu")
    }
    curseforge {
        projectId = "639198"
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        minecraftVersions.add("${project.minecraft_version}")

        requires("fabric-api")
        requires("pulsar")
        optional("cloth-config")
        optional("modmenu")
    }
    github {
        repository = "constellation-mc/andromeda"
        accessToken = providers.environmentVariable("GITHUB_TOKEN")
        commitish = providers.environmentVariable("GITHUB_SHA").getOrElse("${project.minecraft_version}-fabric")

        type = STABLE
    }

    dryRun = local
}