[libraries]
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version = "0.19.3" }

fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version = "0.153.0+26.2" }
pulsar = { group = "dev.zenfyr", name = "pulsar-fabric", version = "1.0.0+mc26.2" }

modmenu = { group = "com.terraformersmc", name = "modmenu", version = "20.0.0-beta.4" }
cloth-config = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version = "26.2.155" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version = "1.17.12" }
lombok = { id = "io.freefair.lombok", version = "9.4.0"}
spotless = { id = "com.diffplug.spotless", version = "8.4.0" }
modmuss50-publish = { id = "me.modmuss50.mod-publish-plugin", version = "1.1.0" }