[libraries]
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version = "0.18.1" }

fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version = "0.92.6+1.20.1" }
pulsar = { group = "dev.zenfyr", name = "pulsar", version = "0.2.0-1.20.1-build.8" }

modmenu = { group = "com.terraformersmc", name = "modmenu", version = "7.2.1" }
cloth-config = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version = "11.1.106" }

handy-tests = { group = "me.melontini", name = "handy-tests", version = "0.2.0-1.20.1-build.9" }

[plugins]
fabric-loom = { id = "fabric-loom", version = "1.14.10" }
lombok = { id = "io.freefair.lombok", version = "9.1.0"}
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
modmuss50-publish = { id = "me.modmuss50.mod-publish-plugin", version = "1.1.0" }