[libraries]
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version = "0.19.2" }

fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version = "0.138.4+1.21.10" }
pulsar = { group = "dev.zenfyr", name = "pulsar", version = "0.2.2-1.21.10-local" }

modmenu = { group = "com.terraformersmc", name = "modmenu", version = "16.0.1" }
cloth-config = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version = "20.0.149" }

[plugins]
fabric-loom = { id = "fabric-loom", version = "1.16.1" }
lombok = { id = "io.freefair.lombok", version = "9.4.0"}
spotless = { id = "com.diffplug.spotless", version = "8.4.0" }
modmuss50-publish = { id = "me.modmuss50.mod-publish-plugin", version = "1.1.0" }