blank_issues_enabled: false
contact_links:
  - name: Suggesting Ideas | 💡
    url: https://github.com/melontini/andromeda/discussions/categories/ideas
    about: If you have a suggestion, please post it here. Be sure to check pinned to see how to make a good suggestion!
