blank_issues_enabled: false
contact_links:
  - name: Ideas Discussions | 💡
    url: https://github.com/melontini/andromeda/discussions/categories/ideas
    about: If you have a suggestion, please post it there. Be sure to check pinned to see if suggestions are open!
